FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# ACMS OpenAPI

# Group Users

## 注册后台用户账号 [/master/save.do]

### 注册信息 [POST]

+ Request (application/json)

        {
            "email":"email@21cn.com",
            "name": "name"
        }
        
+ Response 200 (application/json)
    
        [
            {
            
            }
        】

## 后台用户验证 [/auth/login.do]

### 用户登录 [POST]

    
+ Request (application/json)

        {
        "login":"login",
        "passwd":"passwd"
        }
        

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]